"""
Paa-Nii Hesse's Number Guessing Game
March 6th 2022
Paa-nii Hesse
"""



import tkinter as tk
import random
 
def update_result(text):
    result.configure(text=text)
def new_game():
# # Changes The State of the guess button
    guess_button.config(state='normal')
## The Global Varibles
    global TARGET, RETRIES
## The number generated by the computer
    TARGET = random.randint(0, 150)
## The Reset when game ends
    RETRIES = 0
    update_result(text="Guess a number between 1 and 150")
        
def play_game():
    global RETRIES
    choice = int(number_form.get())
    if choice != TARGET:
        RETRIES += 1
        result = "ERRRR WRONGGGGGGGGGGG"
        if TARGET < choice:
            hint = "Guess lower".format(result)
        if TARGET > choice:
            hint = "Guess Higher".format(choice)
        result += "\n\nHINT :\n" + hint
    else:
        result = "DING DING You guessed the number correctly, HERE HAVE A COOKIE Thank you for playing my number guessing game number. it took you {} retries".format(RETRIES)
        # The Set Stays Normal
        guess_button.configure(state='normal')
        result += "\n" + "Click on Play to start a new game"
     
    update_result(result)
 

window = tk.Tk()
# The new Window
window.geometry("600x400")
# Sets the size of the Window
window.config(bg="DodgerBlue")
# Sets The Colour of the Background
window.resizable(width=False,height=False)
# Set Window Title
title = tk.Label(window,text="Guess a number from 1 to 150",font=("Arial",24),fg="Orange",bg="#065569")
# The Code for the buttons and texts.
result = tk.Label(window, text="Click on Play to start a new game", font=("Arial", 12, "normal", "italic"),fg = "White", bg="#065569", justify=tk.LEFT)
# Play button 
play_button = tk.Button(window, text="Play Game", font=("Arial", 14, "bold"), fg = "Green", bg="#29c70a", command=new_game)
# Guess buton
guess_button = tk.Button(window,text="Guess",font=("Arial",13), state='disabled', fg="Blue",bg="Blue", command=play_game)
# Exit Buton
exit_button = tk.Button(window,text="Exit Game",font=("Arial",14), fg="Red", bg="#b82741", command=exit)
# Entry Box
guessed_number = tk.StringVar()
# Places The labels
number_form = tk.Entry(window,text="Enter You Number",font=("Arial",11),textvariable=guessed_number)
title.place(x=170, y=50)
result.place(x=180, y=210)
# Places the button
exit_button.place(x=300,y=320)
guess_button.place(x=350, y=147) 
play_button.place(x=170, y=320)
# Places the entry field
number_form.place(x=180, y=150)
window.mainloop()
# Start window




